/**
 * Generates docs/chart-system/coverage.{json,md} and behavior.md from the real
 * settings catalog and the executable behavior rules.
 * Run with `npm run coverage:report`. Probes build real models, so the report
 * reflects current renderer behaviour rather than a hand-maintained list.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { CHART_ASSETS } from "../src/charts/assets";
import { BEHAVIOR_RULES, runBehaviorRules } from "../src/charts/behavior";
import { coverageForAsset, EXTENSIONS, LAB_CONTROLS, summarize, type CoverageEntry, type CoverageStatus } from "../src/charts/coverage";
import { BUILT_IN_SCENARIOS } from "../src/charts/scenarios";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = resolve(root, "docs/chart-system");
mkdirSync(outDir, { recursive: true });

const STATUS_LABEL: Record<CoverageStatus, string> = {
  "implemented-verified": "Implemented and verified",
  "implemented-unverified": "Implemented, unverified",
  missing: "Missing",
  "invalid-combination": "Invalid combination",
  "not-applicable": "Not applicable",
};

const started = Date.now();
const perAsset = CHART_ASSETS.map((a) => ({ asset: a, entries: coverageForAsset(a.visualId) }));
const all: CoverageEntry[] = perAsset.flatMap((p) => p.entries);
const total = summarize(all);
const ms = Date.now() - started;

writeFileSync(
  resolve(outDir, "coverage.json"),
  JSON.stringify(
    {
      version: 1,
      generatedAt: new Date().toISOString(),
      entries: all.length,
      summary: total,
      labControls: LAB_CONTROLS,
      extensions: EXTENSIONS,
      assets: perAsset.map((p) => ({ visualId: p.asset.visualId, label: p.asset.label, summary: summarize(p.entries), entries: p.entries })),
    },
    null,
    1,
  ),
);

const esc = (s: unknown) => String(s ?? "").replace(/\|/g, "\\|").replace(/\n/g, " ");
const fmtDefault = (v: unknown) => (v === undefined || v === null || v === "" ? "—" : typeof v === "object" ? "(object)" : esc(v).slice(0, 40));
const lines: string[] = [];
lines.push("# Chart property coverage");
lines.push("");
lines.push(`Generated by \`npm run coverage:report\` from \`src/visualSettingsCatalog.ts\`. Do not edit by hand. ${all.length} entries (asset × field, plus nested palette and flag properties) across ${CHART_ASSETS.length} assets; probing took ${ms} ms.`);
lines.push("");
lines.push("Status meanings:");
lines.push("");
lines.push("- **Implemented and verified**: a probe changed the field on a real fixture and the chart model changed, or a named behavior rule or test covers it.");
lines.push("- **Implemented, unverified**: the renderer reads the field, but no probe or rule shows an observable effect yet.");
lines.push("- **Missing**: the catalog offers the field for this asset, but the renderer does not read it.");
lines.push("- **Invalid combination**: the field cannot apply to this asset as configured; the inspector explains why.");
lines.push("- **Not applicable**: the field has no visual meaning for this asset (for example map-only controls).");
lines.push("");
lines.push("## Summary");
lines.push("");
lines.push("| Asset | Verified | Unverified | Missing | Invalid | N/A | Total |");
lines.push("| --- | ---: | ---: | ---: | ---: | ---: | ---: |");
for (const p of perAsset) {
  const s = summarize(p.entries);
  lines.push(`| ${p.asset.label} (\`${p.asset.visualId}\`) | ${s["implemented-verified"]} | ${s["implemented-unverified"]} | ${s.missing} | ${s["invalid-combination"]} | ${s["not-applicable"]} | ${p.entries.length} |`);
}
lines.push(`| **All** | **${total["implemented-verified"]}** | **${total["implemented-unverified"]}** | **${total.missing}** | **${total["invalid-combination"]}** | **${total["not-applicable"]}** | **${all.length}** |`);
lines.push("");
lines.push(`Behavior rules: ${BEHAVIOR_RULES.length}. Built-in scenarios: ${BUILT_IN_SCENARIOS.length}.`);
lines.push("");
lines.push("## Entries that are not verified");
lines.push("");
lines.push("Verified entries are listed in `coverage.json`. Everything else is listed here with its reason, so gaps are visible rather than averaged away.");
for (const p of perAsset) {
  const open = p.entries.filter((e) => e.status !== "implemented-verified");
  if (!open.length) continue;
  lines.push("");
  lines.push(`### ${p.asset.label}`);
  lines.push("");
  lines.push("| Key | Control | Default | Units | Status | Reason / note |");
  lines.push("| --- | --- | --- | --- | --- | --- |");
  for (const e of open) lines.push(`| \`${esc(e.key)}${e.nested ? ` › ${esc(e.nested)}` : ""}\` | ${esc(e.control)} | ${fmtDefault(e.resolvedDefault)} | ${esc(e.units ?? "—")} | ${STATUS_LABEL[e.status]} | ${esc(e.note ?? e.implementation)} |`);
}
lines.push("");
lines.push("## Lab controls (not product properties)");
lines.push("");
lines.push("| ID | Control | Values | Purpose |");
lines.push("| --- | --- | --- | --- |");
for (const c of LAB_CONTROLS) lines.push(`| \`${c.id}\` | ${c.name} | ${esc(c.values)} | ${esc(c.purpose)} |`);
lines.push("");
lines.push("## Product extensions (not in the saved catalog)");
lines.push("");
lines.push("| ID | Extension | Applies to | Default | Compatibility |");
lines.push("| --- | --- | --- | --- | --- |");
for (const x of EXTENSIONS) lines.push(`| \`${x.id}\` | ${x.name} | ${x.appliesTo.length > 3 ? "All chart assets" : x.appliesTo.join(", ")} | ${x.default ? "On" : "Off"} | ${esc(x.compatibility)} |`);
lines.push("");
writeFileSync(resolve(outDir, "coverage.md"), lines.join("\n"));

const ruleResults = runBehaviorRules();
const areas = [...new Set(ruleResults.map((r) => r.area))];
const b: string[] = [
  "# Behavior rules",
  "",
  "Generated by `npm run coverage:report` from `src/charts/behavior.ts`. Each rule runs the real derivation and layout code; the Lab's Behavior tab and `src/charts/__tests__/behavior.test.ts` read the same list, and every rule links to a scenario that reproduces it.",
  "",
  `${ruleResults.filter((r) => r.result.pass).length} of ${ruleResults.length} rules pass.`,
  "",
];
for (const area of areas) {
  b.push(`## ${area}`, "");
  for (const r of ruleResults.filter((x) => x.area === area)) {
    b.push(`### \`${r.id}\` ${r.result.pass ? "(passes)" : "(FAILS)"}`, "");
    b.push(`- **When**: ${r.when}`);
    b.push(`- **Expected**: ${r.expected}`);
    b.push(`- **Reason**: ${r.reason}`);
    b.push(`- **Scenario**: \`${r.scenarioId}\` — open with \`#/chart-lab?s=id:${r.scenarioId}\``);
    if (r.covers.length) b.push(`- **Covers**: ${r.covers.map((c) => `\`${c}\``).join(", ")}`);
    b.push(`- **Last result**: ${esc(r.result.detail)}`, "");
  }
}
writeFileSync(resolve(outDir, "behavior.md"), b.join("\n"));

console.log(`coverage: ${all.length} entries in ${ms} ms`, total);
console.log(`behavior: ${ruleResults.filter((r) => r.result.pass).length}/${ruleResults.length} rules pass`);
